### PR TITLE
pinentry: Handle percent-encoded responses

### LINKED ISSUE #1: Missing percent-escaping on the data line response
First of all, thanks for these bindings! They're a pleasure to use.

The [Assuan protocol](https://gnupg.org/documentation/manuals/assuan/Server-responses.html) documents that certain characters *must* be percent-escaped, and that others *may* be:

> Raw data returned to client. There must be exactly one space after the ’D’. The values for ’%’, CR and LF must be percent escaped; these are encoded as %25, %0D and %0A, respectively. Only uppercase letters should be used in the hexadecimal representation. Other characters may be percent escaped for easier debugging. All Data lines are considered one data stream up to the OK or ERR response. Status and Inquiry Responses may be mixed with the Data lines. 

Experimentally, pinentry.rs fails to unescape these sequences, mangling the user's input if it happens to contain escaped characters. I took a quick glance at the code, and it looks like the escaping *probably* needs to happen here:

https://github.com/str4d/pinentry-rs/blob/030601d07345ef415aba3715d07f190bc29cc438/src/assuan.rs#L194

I'm happy to take a stab at fixing this.

### PR DESCRIPTION
**Pull request by woodruffw**
Here's my attempt at fixing the issue identified in #1.

It uses the [`percent-encoding`](https://github.com/servo/rust-url/) crate, which appears to be relatively popular (and is maintained by the Servo team).

Fixes #1.

### CODE REVIEW

File: src/assuan.rs [hunk 1]
```diff
@@ -118,7 +119,9 @@ impl Connection {
                 Response::Comment(comment) => debug!("< # {}", comment),
                 Response::DataLine(data_line) => {
                     let buf = data.take();
-                    data = Some(buf.unwrap_or_else(String::new) + data_line.expose_secret());
+                    let data_line_decoded =
```
Comment (woodruffw) [inline src/assuan.rs:123]: N.B. I could `map` this back into a `SecretString`, but I figure that it's already being built up into the (unprotected) `data` string, which eventually gets secretized before being returned. Let me know what you think.

**Comment by woodruffw** [comment]
@str4d gentle ping on this :slightly_smiling_face:

File: src/assuan.rs (hunk 1 above)
Comment (str4d) [reply src/assuan.rs:123]: `SecretString`'s usage here is to ensure that the secret is zeroed out when dropped. `data_line_decoded` is a `Cow<str>`, so the ideal strategy here would be:
```rust
data = ...; // use data_line_decoded
if data_line_decoded.is_owned() {
    data_line_decoded.into_owned().zeroize();
}
```

**Review by str4d — CHANGES_REQUESTED** [review]
Nice PR, thanks! Will merge and release once the new temporary is zeroized.

File: src/assuan.rs (hunk 1 above)
Comment (woodruffw) [reply src/assuan.rs:123]: SGTM! I'll make that change.

Comment (woodruffw) [reply src/assuan.rs:123]: Looks like `Cow::is_owned` hasn't been stabilized yet, so I went with: `if let Cow::Owned(...) = ... { ... }`.

**Review by str4d — APPROVED** [review]

**Comment by woodruffw** [comment]
Thanks for the merge!

**Comment by woodruffw** [comment]
(P.S.: Any chance for a minor release after this fix? It'd be nice to upstream this :slightly_smiling_face:)

**Comment by str4d** [comment]
The release is already out 🙂

**Comment by woodruffw** [comment]
Awesome! Thanks again.
